Repository capsulajs/capsulahub-core, pull requests merged in 2019-05, with the labels that each got.

#5 Feature/init repo
  .gitignore
  .npmignore
  .prettierignore
  .prettierrc.js
  .remarkrc
  jest.config.js
  lerna.json
  package.json
  packages/template/package.json
  packages/template/src/api/.gitkeep
  packages/template/tests/features/.gitkeep
  packages/template/tests/implementations/.gitkeep
  tsconfig.json
  tsconfig.lint.json
  tslint.json
  yarn.lock
Labels: enhancement

#7 Renderer API
  packages/renderer/package.json
  packages/renderer/src/api/Renderer.ts
  packages/renderer/src/api/RendererConfig.ts
  packages/renderer/src/api/index.ts
  packages/renderer/src/api/methods/RenderItemRequest.ts
  packages/renderer/src/api/methods/RenderItemsRequest.ts
  packages/renderer/src/api/methods/RenderLayoutsRequest.ts
  packages/renderer/src/api/methods/index.ts
  packages/renderer/src/index.ts
  packages/renderer/tests/features/.gitkeep
  packages/renderer/tests/implementations/.gitkeep
  packages/renderer/tsconfig.json
Labels: API Proposal

#15 Init Orchestrator API according to the issue
  packages/orchestrator/package.json
  packages/orchestrator/src/api/Flow.ts
  packages/orchestrator/src/api/Orchestrator.ts
  packages/orchestrator/src/api/OrchestratorConfig.ts
  packages/orchestrator/src/api/index.ts
  packages/orchestrator/src/api/methods/init.ts
  packages/orchestrator/src/index.ts
  packages/orchestrator/tests/features/.gitkeep
  packages/orchestrator/tests/implementations/.gitkeep
  packages/orchestrator/tsconfig.json
Labels: API Proposal

#17 Test cases for Orchestrator
  packages/orchestrator/tests/features/orchestrator.feature
Labels: Test cases

#12 [Feature] Enable TravisCI
  .travis.yml
  package.json
  packages/orchestrator/package.json
  packages/renderer/package.json
  packages/template/package.json
  packages/workspace/package.json
  scripts/deploy.sh
  scripts/gh.sh
  scripts/publish.sh
Labels: enhancement

#20 Enable deploy on dev branch
  .travis.yml
Labels: enhancement

#27 [ Feature ] Enable npm publication
  .travis.yml
  scripts/deploy.sh
  scripts/gh.sh
Labels: enhancement

#31 [ Fix ] npm publish for dev branch
  scripts/publish.sh
Labels: bug
